[package]
name = "scramble"
version = "0.1.0"
authors = ["outfrost"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
webster = "0.3.0"
